In [1]:
!git clone https://github.com/yacinemebarki/talk_like_me_gpt

fatal: destination path 'talk_like_me_gpt' already exists and is not an empty directory.


In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/talk_like_me_gpt/data/message.csv")
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88732,وشنوا,Yacine Mebarki,1665091715875
88733,؟؟؟؟,Yacine Mebarki,1665091659314
88734,ياسين,Instagram User,1665091578941
88735,وش عبدو,Yacine Mebarki,1665000590565


In [4]:
print(len(np.unique(df["sender"])))

203


In [5]:
print(len(np.unique(df["content"])))

53172


In [6]:
import re

def clean(mes):
  pattern = re.compile(r"(http[s]?://\S+)|[^\x00-\x7F]")
  return bool(pattern.search(mes))

In [7]:
df=df[df["content"].apply(clean)==False]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
88718,Mat7rshsh,Yacine Mebarki,1663535817836
88719,Instagram User sent an attachment.,Instagram User,1666436431597
88720,Instagram User sent an attachment.,Instagram User,1666254455735
88721,Instagram User sent an attachment.,Instagram User,1666252975962


In [8]:
df=df.reset_index()
df

,index,content,sender,time
0,0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,2,Lala,Yacine Mebarki,1750440185876
3,3,Wesh 5o,Yacine Mebarki,1750440085631
4,4,You missed an audio call,Instagram User,1750440059051
...,...,...,...,...
66156,88718,Mat7rshsh,Yacine Mebarki,1663535817836
66157,88719,Instagram User sent an attachment.,Instagram User,1666436431597
66158,88720,Instagram User sent an attachment.,Instagram User,1666254455735
66159,88721,Instagram User sent an attachment.,Instagram User,1666252975962


In [9]:
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
...,...,...,...
66156,Mat7rshsh,Yacine Mebarki,1663535817836
66157,Instagram User sent an attachment.,Instagram User,1666436431597
66158,Instagram User sent an attachment.,Instagram User,1666254455735
66159,Instagram User sent an attachment.,Instagram User,1666252975962


In [10]:
df.head(10)

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,You missed an audio call,Instagram User,1750440059051
5,Audio call started,Instagram User,1750440042297
6,Yacin,Instagram User,1750440008927
7,3endi shghl dok,Yacine Mebarki,1750087644305
8,Man9dersh,Yacine Mebarki,1750087636879
9,Ntl3o oumb3d nontrino chwiya,Instagram User,1750078313534


In [11]:
df["content"]

,content
0,Sma7li ykho mnkonsh fdar flil 3endi shghl
1,Yacine Lyom 3aa 9
2,Lala
3,Wesh 5o
4,You missed an audio call
...,...
66156,Mat7rshsh
66157,Instagram User sent an attachment.
66158,Instagram User sent an attachment.
66159,Instagram User sent an attachment.


In [12]:
print(len(df[df["content"]=="You missed an audio call"]))
count=df['content'].str.contains('sent an attachment', case=False, na=False).sum()
print(count)
print(len(df[df["content"]=="You started an audio call"]))


290
8938
391


In [13]:
df=df[~(df["content"].str.contains('sent an attachment',case=False,na=False)|
      (df["content"]=="You missed an audio call")|
      (df["content"]=="You started an audio call")|
        (df["content"]=="Audio call started")|
        (df["content"]=="Audio call ended")|
        (df["content"].str.contains('started an audio call',case=False,na=False))|
        (df["content"]=="Liked a message"))]
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
6,Yacin,Instagram User,1750440008927
...,...,...,...
66152,Zino ousama tan,W🩸,1663535934578
66153,Rayne than darha story,Yacine Mebarki,1663535914924
66154,Makach mnha,W🩸,1663535862990
66155,Hhh,W🩸,1663535849006


In [14]:
df=df.reset_index()
df=df.drop(columns=["index"])
df

,content,sender,time
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635
1,Yacine Lyom 3aa 9,Instagram User,1752244626530
2,Lala,Yacine Mebarki,1750440185876
3,Wesh 5o,Yacine Mebarki,1750440085631
4,Yacin,Instagram User,1750440008927
...,...,...,...
53278,Zino ousama tan,W🩸,1663535934578
53279,Rayne than darha story,Yacine Mebarki,1663535914924
53280,Makach mnha,W🩸,1663535862990
53281,Hhh,W🩸,1663535849006


In [15]:
df['next_content'] = df['content'].shift(-1)
df['next_sender'] = df['sender'].shift(-1)

In [16]:
df

,content,sender,time,next_content,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,W🩸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,W🩸
53280,Makach mnha,W🩸,1663535862990,Hhh,W🩸
53281,Hhh,W🩸,1663535849006,Mat7rshsh,Yacine Mebarki


In [17]:
df.rename(columns={"content":"answer","next_content":"message"}, inplace=True)
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
1,Yacine Lyom 3aa 9,Instagram User,1752244626530,Lala,Yacine Mebarki
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
4,Yacin,Instagram User,1750440008927,3endi shghl dok,Yacine Mebarki
...,...,...,...,...,...
53278,Zino ousama tan,W🩸,1663535934578,Rayne than darha story,Yacine Mebarki
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,W🩸
53280,Makach mnha,W🩸,1663535862990,Hhh,W🩸
53281,Hhh,W🩸,1663535849006,Mat7rshsh,Yacine Mebarki


In [18]:
df=df[df["sender"]=="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
2,Lala,Yacine Mebarki,1750440185876,Wesh 5o,Yacine Mebarki
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
5,3endi shghl dok,Yacine Mebarki,1750087644305,Man9dersh,Yacine Mebarki
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
...,...,...,...,...,...
53273,Wesh wadoud tji 3shya,Yacine Mebarki,1731156585337,Ok,Yacine Mebarki
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,W🩸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,W🩸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,W🩸


In [19]:
df=df[df["next_sender"]!="Yacine Mebarki"]
df

,answer,sender,time,message,next_sender
0,Sma7li ykho mnkonsh fdar flil 3endi shghl,Yacine Mebarki,1752245800635,Yacine Lyom 3aa 9,Instagram User
3,Wesh 5o,Yacine Mebarki,1750440085631,Yacin,Instagram User
6,Man9dersh,Yacine Mebarki,1750087636879,Ntl3o oumb3d nontrino chwiya,Instagram User
8,Lala,Yacine Mebarki,1750078181154,Makch tontrini,Instagram User
10,Wlah walou mkash ga3,Yacine Mebarki,1750078074006,Yacin kach match,Instagram User
...,...,...,...,...,...
53271,Asm3 rani fi plassa champ na9ss,Yacine Mebarki,1731520839382,Ih,W🩸
53274,Ok,Yacine Mebarki,1685647730830,B3atilou,W🩸
53277,Zinou hbt m3aya lljam3,Yacine Mebarki,1663535955943,Zino ousama tan,W🩸
53279,Rayne than darha story,Yacine Mebarki,1663535914924,Makach mnha,W🩸


In [20]:
df=df.dropna(subset=['message', 'answer'])

In [21]:
df.iloc[30:50]

,answer,sender,time,message,next_sender
90,Rigle,Yacine Mebarki,1765919575586,Fiha,⭕️
93,Asm3 ji tl3b ghdwa and ali 3la 20,Yacine Mebarki,1765919545080,Ni khrg deka,⭕️
96,Ana then haji 5arj,Yacine Mebarki,1759604173430,Aya riglha khu,⭕️
99,Aya rigle fiha,Yacine Mebarki,1759596864250,Nji,⭕️
102,Ya5i rouf yji,Yacine Mebarki,1759596848247,Riglha shby,⭕️
104,aya oumb3ed ntl9awe fstad direct,Yacine Mebarki,1759596796160,Rigkha khu,⭕️
111,Wesh ramzi,Yacine Mebarki,1759595591747,Aya riglha hbb,⭕️
113,Dok nshouf Ida ran 9l men 9 3ytlou,Yacine Mebarki,1741611849180,Ay yasine neayt raouf na3mni yji yl3b m3ana,⭕️
117,Kima malf mour l3asser,Yacine Mebarki,1741552887267,39dach,⭕️
122,Aya rigle,Yacine Mebarki,1740585493897,9al wsdoud ih,⭕️


In [22]:
from tensorflow.keras import layers,models
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df=df.reset_index()
df=df.drop(columns=["index"])

In [25]:
x=df["message"]
y=df["answer"]

In [26]:
import tensorflow as tf
def normmalize(text):
  text=tf.strings.lower(text)


  return text

In [27]:
print(dir(TextVectorization))

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_trackable_child', '_add_variable_with_custom_getter', '_api_export_path', '_api_export_symbol_id', '_assert_input_compatibility', '_build_at_init', '_build_by_run_for_kwargs', '_build_by_run_for_single_pos_arg', '_check_quantize_args', '_check_super_called', '_checkpoint_adapter', '_checkpoint_dependencies', '_clear_losses', '_copy_trackable_to_cpu', '_default_save_signature', '_deferred_dependencies', '_delete_tracking', '_deserialization_dependencies', '_deserialize_from_proto', '_export_to_saved_model_graph', '_flatten_layers', '_float8_call', '_gather_saveables_for_checkpoint', '_get_call_context', '_get_node_

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [29]:
question=x_test
res=y_test

In [30]:
tok_m=TextVectorization(output_sequence_length=32,standardize=normmalize)
tok_a=TextVectorization(output_sequence_length=32,standardize=normmalize)
tok_m.adapt(x_train)
tok_a.adapt(y_train)

In [31]:
x_seq=tok_m(x_train)
y_seq=tok_a(y_train)

In [32]:
x_seq

<tf.Tensor: shape=(10811, 32), dtype=int64, numpy=
array([[ 774, 5267,    0, ...,    0,    0,    0],
       [  11,    0,    0, ...,    0,    0,    0],
       [3298,   43,  465, ...,    0,    0,    0],
       ...,
       [ 208, 7080,  155, ...,    0,    0,    0],
       [   2,    0,    0, ...,    0,    0,    0],
       [   3,   22, 1164, ...,    0,    0,    0]])>

In [33]:
np.argmax(x_seq[0])

np.int64(1)

In [34]:
x_seq=pad_sequences(x_seq,maxlen=32)
y_seq=pad_sequences(y_seq,maxlen=32)

In [35]:
print(x_seq)

[[ 774 5267    0 ...    0    0    0]
 [  11    0    0 ...    0    0    0]
 [3298   43  465 ...    0    0    0]
 ...
 [ 208 7080  155 ...    0    0    0]
 [   2    0    0 ...    0    0    0]
 [   3   22 1164 ...    0    0    0]]


In [36]:
y_test

,answer
2471,Nazim y3lb ghdw fjsbb
10657,Shwakr
12557,1% ta3 attlitico 9is ml3bou centre
11497,Ra7 yl3bhom match bmatch bash ykthrsh l7ss
5034,Blamzya
...,...
8651,cos ykoun b radian tsma ilzm t7wl
5835,Ana kont jay hadak lw9t ki 3endi malaya sba7 r...
3169,Aya oumb3ed
883,Ran 5arj m3a dar


In [37]:
model=models.Sequential()
model.add(layers.Embedding(input_dim=len(tok_m.get_vocabulary())+1,output_dim=32))
model.add(layers.SimpleRNN(64,return_sequences=True))
model.add(layers.TimeDistributed(layers.Dense(len(tok_a.get_vocabulary())+1,activation="softmax")))

In [38]:
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy")

In [39]:
model.fit(x_seq,y_seq,epochs=5,batch_size=32)

Epoch 1/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 40ms/step - loss: 3.7284
Epoch 2/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 1.0468
Epoch 3/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.9463
Epoch 4/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - loss: 0.9094
Epoch 5/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.8795


In [40]:
x_test

,message
2471,Kachma sha9it ?
10657,Rah 9labha ki cristiano
12557,Ki l3ada
11497,Haland roddri md5loch
5034,Mrc
...,...
8651,Wchno hada
5835,7:30
3169,Rigl
883,Tzid


In [41]:
x_test=tok_m(x_test)
y_test=tok_a(y_test)

x_test=pad_sequences(x_test,maxlen=32)



In [42]:
x_test

array([[ 436,    1,   11, ...,    0,    0,    0],
       [  47,    1,   25, ...,    0,    0,    0],
       [  25, 2449,    0, ...,    0,    0,    0],
       ...,
       [  42,    0,    0, ...,    0,    0,    0],
       [1915,    0,    0, ...,    0,    0,    0],
       [   1,    1,  557, ...,    0,    0,    0]], dtype=int32)

In [43]:
y_test

<tf.Tensor: shape=(2703, 32), dtype=int64, numpy=
array([[ 107,    1, 1209, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,   10, 2656, ...,    0,    0,    0],
       ...,
       [  33,   51,    0, ...,    0,    0,    0],
       [1426,  277,   28, ...,    0,    0,    0],
       [   1,   67,    0, ...,    0,    0,    0]])>

In [44]:
pred=model.predict(x_test)
pred=np.argmax(pred,axis=2)

85/85 ━━━━━━━━━━━━━━━━━━━━ 8s 60ms/step


In [45]:
pred

array([[4, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       ...,
       [6, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0]])

In [46]:
vocab=tok_a.get_vocabulary()
print(vocab[4])
print(vocab[6])
print(len(np.unique(pred)))

aihe
asm3
7


In [47]:
print(pred.shape)

(2703, 32)


In [48]:
print(model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 32, 32)         │       334,976 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 32, 64)         │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ time_distributed                │ (None, 32, 8677)       │       564,005 │
│ (TimeDistributed)               │                        │               │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,715,569 (10.36 MB)

 Trainable params: 905,189 (3.45 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,810,380 (6.91 MB)

None


In [49]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,AdditiveAttention,Concatenate

In [50]:
encoder_input=Input(shape=(32,))
encoder_emb=layers.Embedding(input_dim=len(tok_m.get_vocabulary())+1,output_dim=32)(encoder_input)
encoder_gru,encoder_state=layers.GRU(64,return_state=True,return_sequences=True)(encoder_emb)

print(f"Type of encoder_state: {type(encoder_state)}")
print(f"Shape of encoder_state: {encoder_state.shape}")

Type of encoder_state: <class 'keras.src.backend.common.keras_tensor.KerasTensor'>
Shape of encoder_state: (None, 64)


In [51]:
decoder_inp=Input(shape=(32,))
decoder_emb=layers.Embedding(input_dim=len(tok_a.get_vocabulary())+1,output_dim=32)(decoder_inp)
decoder_gru,decoder_state=layers.GRU(64,return_state=True,return_sequences=True)(decoder_emb)

densel=layers.Dense(len(tok_a.get_vocabulary())+1,activation="softmax")(decoder_gru)

In [52]:
pip=Model([encoder_input,decoder_inp],densel)

In [53]:
pip.compile(optimizer="adam",loss="sparse_categorical_crossentropy", run_eagerly=True)

In [54]:
x_seq = np.array(x_seq, dtype=np.int32)
y_seq = np.array(y_seq, dtype=np.int32)

In [55]:
print(x_seq.shape)
print(y_seq.shape)

(10811, 32)
(10811, 32)


In [56]:
pip.fit([np.array(x_seq),np.array(y_seq)],y_seq,batch_size=32,epochs=5)

Epoch 1/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 28s 76ms/step - loss: 3.6526
Epoch 2/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 77ms/step - loss: 0.8328
Epoch 3/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.7479
Epoch 4/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.6837
Epoch 5/5
338/338 ━━━━━━━━━━━━━━━━━━━━ 26s 76ms/step - loss: 0.6224


In [57]:
pred=pip.predict([x_test,y_test])
pred

85/85 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step


array([[[6.7737967e-02, 4.0598206e-06, 5.5932864e-03, ...,
         4.8801826e-06, 4.0909481e-06, 4.2383876e-06],
        [4.3853826e-05, 2.0681888e-05, 7.0776177e-06, ...,
         5.3940352e-05, 4.6954268e-05, 2.0254436e-05],
        [1.6683262e-07, 3.1271782e-05, 6.9958116e-07, ...,
         1.1562153e-04, 1.4390342e-04, 3.1431206e-05],
        ...,
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09],
        [9.9766845e-01, 3.9557237e-09, 6.4119777e-06, ...,
         5.1744524e-09, 3.6449415e-09, 4.0538128e-09]],

       [[3.8550084e-04, 6.8559202e-05, 1.9242259e-04, ...,
         9.9403987e-05, 9.7857061e-05, 6.8487767e-05],
        [9.9651742e-01, 6.9108403e-09, 7.5944367e-06, ...,
         8.4688558e-09, 5.8495355e-09, 7.0703416e-09],
        [9.9766123e-01, 3.9756034e-09, 6.4228930e-06, ...,
         5.197

In [58]:
pred=np.argmax(pred,axis=2)
pred

array([[  0, 222, 533, ...,   0,   0,   0],
       [ 57,   0,   0, ...,   0,   0,   0],
       [ 57,  10, 533, ...,   0,   0,   0],
       ...,
       [ 33,  40,   0, ...,   0,   0,   0],
       [533,   0,  28, ...,   0,   0,   0],
       [ 57,   0,   0, ...,   0,   0,   0]])

In [59]:
def seq_to_text(seq, vocab):
    return [" ".join(vocab[i] for i in s if i != 0) for s in seq]



In [60]:
answer_vocab=tok_a.get_vocabulary()
for i in range(len(pred)):
  print("question is",question.iloc[i],"resopnse is",seq_to_text([pred[i]],answer_vocab))


question is Kachma sha9it ? resopnse is ['9dah fatt de']
question is Rah 9labha ki cristiano resopnse is ['5lass']
question is Ki l3ada resopnse is ['5lass ta3 fatt de f fatt']
question is Haland roddri md5loch resopnse is ['ra7 7ab li jamber bash jamber m3ana']
question is Mrc resopnse is ['aya']
question is Dok !! resopnse is ['5lass fatt']
question is Cc resopnse is ['oui']
question is Bsh wchbiha cnx dyalkom mkantch haka resopnse is ['aya']
question is Zad myhderch resopnse is ['nl3bou wla 7ab']
question is Doka nta mtrrohche ghdwa 3end w3rab resopnse is ['aihe']
question is 5s rayen resopnse is ['9dah men jamber']
question is Gea bdw ydhko resopnse is ['nta 9dah']
question is Oui yacine sma7li knt msupprimi insta resopnse is ['ok rigle b3tht']
question is Oui resopnse is ['lah ou fatt bash f match message ou fatt']
question is Waktach ndiro match resopnse is ['3la 9dah kipa men jamber m3ana']
question is vu resopnse is ['aihe shared']
question is tji gadwa resopnse is ['lah dok']


In [61]:
y_test

<tf.Tensor: shape=(2703, 32), dtype=int64, numpy=
array([[ 107,    1, 1209, ...,    0,    0,    0],
       [   1,    0,    0, ...,    0,    0,    0],
       [   1,   10, 2656, ...,    0,    0,    0],
       ...,
       [  33,   51,    0, ...,    0,    0,    0],
       [1426,  277,   28, ...,    0,    0,    0],
       [   1,   67,    0, ...,    0,    0,    0]])>

In [62]:
from nltk.translate.bleu_score import sentence_bleu

references = []
candidates = []

for i in range(len(y_test)):
    ref_seq = seq_to_text([y_test[i]], answer_vocab)[0].split()
    pred_seq = seq_to_text([pred[i]], answer_vocab)[0].split()
    references.append([ref_seq])
    candidates.append(pred_seq)


In [63]:
bleu_scores = []

for ref, cand in zip(references, candidates):
    score = sentence_bleu(ref, cand)
    bleu_scores.append(score)

print("Average BLEU:", sum(bleu_scores)/len(bleu_scores))

Average BLEU: 0.0010914320707007578


/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning: 
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning: 
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning: 
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_